version: '3.7'

services:
  # Sendy MySQL database
  db_sendy:
    hostname: sendy_db
    container_name: db_sendy
    image: mysql:5.6
    restart: always
    environment:
      - SENDY_FQDN=sendy.example.com
      - MYSQL_HOST=sendy_db
      - MYSQL_DATABASE=sendy
      - MYSQL_USER=sendy
      - MYSQL_PASSWORD=superstrongpassword
      - MYSQL_ROOT_PASSWORD=superstrongpassword
    volumes:
      - ./sendy_db:/var/lib/mysql

  # Sendy app (Sendy, PHP, Apache2)
  sendy:
    hostname: sendy_app
    container_name: sendy_app
    image: rynaardburger/sendy:latest
    restart: always
    ports:
      - 80:80
    environment:
      - SENDY_FQDN=sendy.example.com
      - MYSQL_HOST=sendy_db
      - MYSQL_DATABASE=sendy
      - MYSQL_USER=sendy
      - MYSQL_PASSWORD=superstrongpassword
    depends_on:
      - db_sendy

volumes:
  sendy_data: